### ISSUE TITLE
Stop now button visible even when start !== true

### ISSUE THREAD

**Issue by srivastavayushi** [ajitkumar1264/Annex-qr-code-simulator#28]
The `stop now` button has no functionality till `start now` button has not been activated.

**Current situation :**  
<img width="321" alt="Screenshot 2022-10-01 at 6 52 25 PM" src="https://user-images.githubusercontent.com/56116708/193411546-84192429-5b45-4ffa-85a9-f2a81c1907cd.png">

**After changes : Before clicking `start now` button : (stop now button not visible since there is no image to stop scanning)** 
<img width="380" alt="Screenshot 2022-10-01 at 6 56 44 PM" src="https://user-images.githubusercontent.com/56116708/193411722-2746d544-60cb-459d-aa7f-e6ae6133701a.png">

**After clicking `start now` button : (stop now button becomes visible)** 
<img width="337" alt="Screenshot 2022-10-01 at 6 56 25 PM" src="https://user-images.githubusercontent.com/56116708/193411705-9e63a6eb-2a93-4229-a237-5cee8afba867.png">

I would like to work on this issue. @ajitkumar1264 please assign this to me.

**Comment by ajitkumar1264** [comment]
@srivastavayushi thanks for your suggestions 👍.

**Comment by srivastavayushi** [comment]
@ajitkumar1264 , solved this issue, kindly have a look at this [pull-request](https://github.com/ajitkumar1264/Annex-qr-code-simulator/pull/72)

**Comment by ajitkumar1264** [comment]
@srivastavayushi thanks.
